[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name="emoflow-tts"
version='0.0.1'
dependencies=[
    "torch",
    "torchaudio",
    "pydantic",
    "pyyaml",
    "pandas",
    "numpy<2"
]
authors = [
    {name = "Jack Jiang"}
]

[project.optional-dependencies]
dev = ["pytest", "ruff", "mypy"]